### ISSUE TITLE
Move from Java source level 8 to source level 11+?

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#102]
I had to move to JDK11 for CI (though source/bin level 1.8) to workaround a strange compiler issue in nested generics for #64 , do we want to move to a later source level?

**Comment by macchiati** [comment]
I think we should stick with LTS versions unless we have a compelling
reason. So that would be JDK 11 for now

https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Mark

**Comment by markusicu** [comment]
I think part of Steven's question is whether we should move up from Java 8 for source & library features.

I believe that no one is using these Unicode Tools as libraries in other projects, so moving up to Java 11 is probably fine.

**Comment by macchiati** [comment]
I read it as:

I had to move to JDK11 ... , do we want to move to a later source level?

(meaning later than JDK11)

Mark

**Comment by srl295** [comment]
> I read it as: I had to move to JDK11 ... , do we want to move to a later source level? (meaning later than JDK11) Mark
> […](#)

I had to move the implementation (the actual installed JDK) from 8 to 11  (in the automated build) due to a compiler bug.  However, Maven is still set to use JDK8 as the source code level and the binary output level. This means JDK9 features, for example, aren't allowed, even though JDK11 is the underlying implementation.

I'm proposing to _explicitly move the source level_ from 8 to 11. We can keep the binary (output) level at 8 if someone would run the jar on an older jdk, that's fine.

What this means is that you would need at least JDK11  to develop.

**Comment by markusicu** [comment]
Discussed in meeting. Ok to try to go to Java 11.

**Comment by srl295** [comment]
CLDR uses JDK11 as of CLDR-14311 (which will land in v42)
