### ISSUE TITLE
What are /bin-props/?

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#103]
ListProps.java has the following:

```java
                    latest.internalStoreCachedMap(Settings.Output.GEN_DIR + "/bin-props/", item, map);
```

`bin-props` never appears anywhere else in the code, and running ListProps fails because this directory doesn't exist.

What does it mean? @macchiati ?

**Comment by srl295** [comment]
Actually it looks like it was just missing a `mkdir`

**Comment by markusicu** [comment]
I suspect that that wants to be changed to 
```
latest.internalStoreCachedMap(Settings.Output.BIN_DIR, item, map);
```
where `BIN_DIR = GEN_DIR + "BIN/"`
unless it has to be separate from the regular BIN dir.

**Comment by srl295** [comment]
> I suspect that that wants to be changed to
> 
> ```
> latest.internalStoreCachedMap(Settings.Output.BIN_DIR, item, map);
> ```
> 
> where `BIN_DIR = GEN_DIR + "BIN/"`
> unless it has to be separate from the regular BIN dir.

I can do that… that changes the binary data output!
