### ISSUE TITLE
fix Unicode Tools after 2021-aug CLDR/ICU update

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#118]
The Unicode Tools are currently broken when using the current CLDR "master" snapshot. Most of the breakages come from changes I made some weeks ago in ICU, and CLDR recently updated to a later ICU snapshot.
- AbbreviatedUnicodeSetIterator overrides base class methods that are now private, not protected (they were `@internal`); I will replace it with other code like I did in an ICU test class
- UnicodeSetParser is a partial clone of ICU UnicodeSet, and thus calls lots of internal methods; we could try to keep this fork of the code parallel, but that seems like an unnecessary maintenance burden. @macchiati do we really need this class?

**Comment by markusicu** [comment]
Discussed: Ok to remove unicodetools/org/unicode/utilities/UnicodeSetParser.java (added in PR #33) -- we can get it back from the repo history.

**Comment by markusicu** [comment]
For the AbbreviatedUnicodeSetIterator copy the changes from https://github.com/unicode-org/icu/pull/1753/files#diff-8fd5cf8924984b5f296dca89f68242ca877f18a25e9b1ff3840f6cf16c804072

**Comment by macchiati** [comment]
sounds good
Mark

**Comment by markusicu** [comment]
fixed
