### ISSUE TITLE
omit UTF-8 signature (BOM) from generated files

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#123]
Ken:

In double-checking all the data files for up-to-date copyright notices,
I stumbled on the fact that *all* of the security data files in the
release (other than the ReadMe.txt) have an unnecessary initial UTF-8
BOM on the file. This appears to be the result of some bogus conversion
step for output somewhere in the generating tools.

This is not a regression, because I checked that it has been the case
for all these files going back at least to Unicode 10.0. But it
definitely should be fixed in the tools, as it is somewhat embarrassing
to be officially recommending against unnecessary initial UTF-8 BOMs in
UTF-8 text files, but then going ahead and using them in the release of
our *security* data files. ;-)

See, e.g. confusables.txt, IdentifierType.txt, intentional.txt in the
security/14.0.0/ directory.

Steven:

ICU and CLDR have automated tools which check for stray BOMs.  These could be used as part of a test case.  If it’s the unicodetools repository that has these files, it could have an automated step to scan - excluding any known historical BOMs. This would prevent check-in of any such files.

**Comment by srl295** [comment]
after #64
