### ISSUE TITLE
make UnicodeJsps depend on unicodetools

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#131]
Once #64 is done, we should change UnicodeJsps to be dependent on unicodetools. This will allow the classes to be present only once and shared between those two.

For part of #66

**Comment by srl295** [comment]
Also move `UnicodeJspsTest` into the UnicodeJsps module

**Comment by markusicu** [comment]
Is this done? Can we close this issue? Or is there more?

**Comment by srl295** [comment]
closing this, i think the remaining work is the UnicodeJspTests and other tests to work on in #146
