### ISSUE TITLE
update JSP to link to new markdown location

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#139]
Also a followon to #132 

@srl295 to update JSP URL to <https://unicode-org.github.io/unicodetools/help/>… per #138

**Comment by srl295** [comment]
When this is done, the JSP won't link into cldr.unicode.org anymore.

**Comment by AEApple** [comment]
@srl295 - I have updated all the pages with a warning that they will be removed from the CLDR Site (Google Site). Please take a look at the draft and publish if you think it looks good, or let me know what further updates are needed? Thanks!

**Comment by srl295** [comment]
May need to pick this up on Monday before I can review

**Comment by AEApple** [comment]
> May need to pick this up on Monday before I can review

Sure

**Comment by AEApple** [comment]
So should I publish the warning on the CLDR site that those pages will be deprecated at the end of CLDR v41 cycle.

**Comment by srl295** [comment]
Yes, please publish it

**Comment by dwsinger** [comment]
will those using the 'old' URL find (a) the new page (b) the old page, with a note of deprecation and a 'please go to' link or (c) a 404?  I hope (a) or (b)?

**Comment by srl295** [comment]
> will those using the 'old' URL find (a) the new page (b) the old page, with a note of deprecation and a 'please go to' link or (c) a 404? I hope (a) or (b)?

The old page is here <https://cldr.unicode.org/unicode-utilities/changes> and it leads back here.  

If you're following that link from the old page, go to <https://unicode-org.github.io/unicodetools/help/>

**Comment by dwsinger** [comment]
The old location is embedded in lots of pages and docs. I am rather keen it not 'stop wotking'. It should redirect or land on a page that has the new location as a prominent link, I think?

**Comment by srl295** [comment]
> The old location is embedded in lots of pages and docs. I am rather keen it not 'stop wotking'. It should redirect or land on a page that has the new location as a prominent link, I think?

Can you give an example of where it's embedded?

**Comment by fantasai** [comment]
> Can you give an example of where it's embedded?

My bookmarks folder, old bug reports and mailing list discussions, probably a lot of "here is more useful-info / references" links on pages belonging to various people/organizations...

> The best we an do is update the link on that page (which points here) to the new help page.

That's not ideal, but it's workable.

> We'd also like to retire the sites page eventually.

Breaking incoming links is Not Cool, particularly for an important reference site such as unicode.org. I'm surprised Unicode Consortium doesn't have some kind of URL persistence policy.

**Comment by dwsinger** [comment]
> Can you give an example of where it's embedded?

As I am sure you appreciate, a large part of the problem is that we don't know all the places it's embedded. But Fantasai gave examples...

**Comment by srl295** [comment]
@fantasai @dwsinger thanks…

Specifically, you have links to `https://cldr.unicode.org/unicode-utilities/changes` bookmarked? or something else (such as the old location of the tool)?

**Comment by srl295** [comment]
I've made a proposed update to cldr.unicode.org that basically looks like this:

> # The Unicode Utilities have moved, please update your bookmarks to point to: https://util.unicode.org/ 

This way people are sent to the stable unicode.org URL.  Comments?

**Comment by srl295** [comment]
@fantasai @dwsinger is there any more recent context? I'm surprised that a 2-year old ticket has suddenly become active.

**Comment by srl295** [comment]
I didn't realize there was a whole subsite on cldr.unicode.org — I've now made proposed changes to _all_ of the pages to look like in my comment https://github.com/unicode-org/unicodetools/issues/139#issuecomment-1857259370

@fantasai 
> URL persistence policy

There's no CDN here, yet, so not a lot of coherency, as these are all disparate hosts on disparate hosting environments, some of which we lack full control over. the most permanent links will be on the `//unicode.org/` host. suggestions definitely welcome though-

**Comment by fantasai** [comment]
> @fantasai @dwsinger is there any more recent context? I'm surprised that a 2-year old ticket has suddenly become active.

No context other than I ran across the problem and commented on it. :)

> Google sites does not provide a redirect mechanism.

HTTP 301 redirects to each page's new location would be ideal, but using a [META http-equiv](https://www.w3.org/TR/WCAG20-TECHS/H76.html) instead should also work; and worst case a bold statement with a link at the top is workable. (If you can't do individual page redirects, then just the bold statement at the top is probably best so people don't get disoriented by getting dumped onto the new home page. Or maybe do individual redirects for the most important/popular pages and a generic one for the rest, if you don't have an available mapping?)

> This way people are sent to the stable unicode.org URL. Comments?

That's definitely much better. Seems it still needs to propagate to e.g. https://cldr.unicode.org/unicode-utilities/list-unicodeset ?

**Comment by srl295** [comment]
> > @fantasai @dwsinger is there any more recent context? I'm surprised that a 2-year old ticket has suddenly become active.
> 
> No context other than I ran across the problem and commented on it. :)

OK thanks!

> 
> > For a reference site, yes. But the Unicode Tools was basically run (and maintained) just as an internal tool. It's not a part of the reference for The Unicode Standard, etc.
> 
> They're not the official standard, but people still use them for reference. :)
> 
> > Google sites does not provide a redirect mechanism.
> 
> HTTP 301 redirects to each page's new location would be ideal, but using a [META http-equiv](https://www.w3.org/TR/WCAG20-TECHS/H76.html) instead should also work; and worst case a bold statement with a link at the top is workable. (If you can't do individual page redirects, then just the bold statement at the top is probably best so people don't get disoriented by getting dumped onto the new home page. Or maybe do individual redirects for the most important/popular pages and a generic one for the rest, if you don't have an available mapping?)

That's interesting. We could see if http-equiv in 'raw' html mode in sites is supported.  FYI @AEApple .

> > This way people are sent to the stable unicode.org URL. Comments?
> 
> That's definitely much better. Seems it still needs to propagate to e.g. https://cldr.unicode.org/unicode-utilities/list-unicodeset ?

It's in the review queue for publication.

**Comment by srl295** [comment]
Pinged everyone on the review queue
