### ISSUE TITLE
Emoji chart fixes

### ISSUE THREAD

**Issue by macchiati** [unicode-org/unicodetools#14]
Drop the sidebar on the index page

---

Fix the links that go to unicode.org/emoji to stay on the tech site

---

The new chart files still have the same 3 non-fatal errors that have been there for a while:
Line 4, Column 15: "ASYNC" is not a member of a group specified for any attribute
```
<script async src='https://www.googletagmanager.com/gtag/js?id=UA-19876713-1'><…
Error Line 4, Column 78: required attribute "TYPE" not specified
…async src='https://www.googletagmanager.com/gtag/js?id=UA-19876713-1'></script>
Error Line 5, Column 8: required attribute "TYPE" not specified
<script>
    ... Typical values for type are type="text/css" for <style> and type="text/javascript" for <script>.

```

----

The following HTML file listing proposals has a few errors, some cascading:
https://www.unicode.org/emoji/flag-charts-13.0-2020-07-23/emoji-proposals.html

E.g, line 31 is:

`<p><b>Caveats:</b> the data is draft, and needs further improvement: suggestions for corrections and other improvements can be submitted at <a target='emoji-proposal-corrections' href='https://docs.google.com/forms/d/e/1FAIpQLSf5RtIkkBP_eUmRFSZfBGm9W6vj2n31_qUzWcv9FXdtyb81kQ/viewform?usp=pp_url&entry.565091389=Add&entry.1700236179=%F0%9F%91%BD&entry.1390707358=L2/99-999'>Emoji Proposal Corrections</a>.</p><p>While these charts use a particular version of the <a target='emoji-data' href='https://unicode.org/Public/emoji/13.0/'>Unicode Emoji data files</a>, the images and format may be updated at any time. For any production usage, consult those data files.  For information about the contents of each column, such as the <b>CLDR Short Name</b>, click on the column header. For further information, see <a target='text' href='index.html'>Index &amp; Help</a>.</p>
`
The source of the validation complaints is probably un-escaped ampersands in URLs, as in the "&entry" in the above line. (I think these don't usually cause browser failure, the validator just doesn't like them.)

----

Emoji-released file https://www.unicode.org/emoji/flag-charts-13.0-2020-07-23/emoji-released.html has an closing </p>, in part of the template:

  Line 25, Column 109: end tag for element "P" which is not open.

I think you want a closing </p> on line 24, just before the phrase "The characters were based on proposals"...

**Comment by markusicu** [comment]
These things appear to be fixed or moot.
