### ISSUE TITLE
Update TestSecurity to have fallback behavior for reading input

### ISSUE THREAD

**Issue by echeran** [unicode-org/unicodetools#151]
Currently, TestSecurity looks for files from the Generated directory. This is because TestSecurity depends on a tool (`GenerateConfusables -c -b`) to be run first to generate those files.

However, now that we have gotten our tests running regularly, these tests are running as unit tests in total isolation from each other. That means that the prerequisites for TestSecurity are broken, which will cause [test failures](https://github.com/unicode-org/unicodetools/pull/136#discussion_r741354229).  A kludgy workaround for CI purposes is to create a symlink in the Generated directory (for tool output files) that points to the input files in the repository source tree, just for the purposes of this TestSecurity test.

Instead, we should fix this test to look for its input files in Generated, as it should, and then fallback to the repository input files to support this temporary issue of failing unit tests. (Perhaps, in the future, we can think about if/how tests with dependencies on tools execution should be best handled in a Maven-compatible way.)

**Comment by markusicu** [comment]
done
