### ISSUE TITLE
omit the -Update suffix from Unicode 15+ data/ucd folder names

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#157]
Starting with Unicode 15, we should name the input data folders for the version number only, without the -Update suffix. "15.0.0", not "15.0.0-Update".

In https://www.unicode.org/Public/ the -Update suffix was last used for Unicode 4.0.1.

This will require a small tweak in org/unicode/text/utility/Utility.java and in Settings.java .

**Comment by macchiati** [comment]
Sgtm
