### ISSUE TITLE
remove MakeUnicodeFiles.DeltaVersion

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#161]
Now that we no longer generate files with versioned suffixes, we should
- delete the `DeltaVersion` line in MakeUnicodeFiles.txt
- remove the `dVersion` field in MakeUnicodeFiles.java
- write UCD output files into Generated/UCD/15.0.0 instead of Generated/UCD/d24

**Comment by macchiati** [comment]
Lgtm
