### ISSUE TITLE
Update CI scripts for new Unicode version

### ISSUE THREAD

**Issue by echeran** [unicode-org/unicodetools#175]
We have a few locations in our `.github/workflows/build-jsp.xml` script that are using the "14.0.0" arg for the version of Unicode ([example](https://github.com/unicode-org/unicodetools/blob/main/.github/workflows/build-jsp.yml#L43)).

Do we need to change this to "15.0.0"? 

If so, should we document a "new Unicode version workflow" similar to how #172 is about documenting the process for new data files / data file updates?

**Comment by markusicu** [comment]
Yes, we need to change it to "15.0.0".

I think a simple PR to change the version number, and to add a sentence in build.md, suffices. build.md already talks about various things to do for a new Unicode version.
