### ISSUE TITLE
assess all classes with main() functions

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#191]
There are more than 300 classes in this repo with `main()` functions. This is many more than the documented tools that we know of. We should review and assess each of them:
- Is it a still-useful unit test? If so, then it should be JUnit-ified and added to CI.
- Is it a still-useful tool? If so, then it should be documented (good class JavaDoc, and/or .md page) and it should at least be *built* in CI.
- Is it still-useful demo or sample code? If so, then it should be documented. Should we collect such classes in a "samples" package?
- Is it obsolete? Then we should delete it, or at least move it to the "unused" package. (org.unicode.unused)

[Spreadsheet: Unicode Tools classes with main()](https://docs.google.com/spreadsheets/d/17_Iln6zQlzNc4pM-kFBcYtkJcSOWkvHk_GI4kDNCpVA/edit#gid=0) started 2021-nov-08

Note progress in the "disposition" column of the spreadsheet. For example, "done: converted to JUnit".
- Steven will do so for tests converted before 2022-jan-10: #190

**Comment by macchiati** [comment]
There is a more fundamental question; given that there appears to be no way
to do this without a lot of effort:

Is this the best use of our time?

Mark

**Comment by markusicu** [comment]
> There is a more fundamental question; given that there appears to be no way to do this without a lot of effort: Is this the best use of our time?

As discussed today, this seems to be one of the most important tasks for the Unicode Tools, because we keep circling back from other code maintenance topics to this issue.

We have a lot of code, and most of us don't have a good handle on what's used, what's important, what's best practice, what's obsolete.

We want to de-duplicate near-copies of classes. When each contains unused code, then we need not figure out how to merge versions of that code that have drifted apart. By deleting obsolete tools more "library" code becomes actually unused.

We want to be able to clean up and refactor code, for example consolidating various utilities. The less code there is, the easier it is to do so.

We want to find still-useful tests, and run them regularly, to avoid inadvertent data bugs.

The Unicode Tools are hard to use and maintain as they are. I thought we had consensus on putting in some amount of work to make them easier to maintain, and easier/more reliable to use via automatic building and testing. In order to do so, we need to get a grip on the top layer, the classes with `main()` functions.

**Comment by markusicu** [comment]
FYI file finder on the commit just before mavenization: https://github.com/unicode-org/unicodetools/find/3d4b442d5385a2d310435923fc81beecd5c3e0c6

**Comment by markusicu** [comment]
Mark and I finished going through the remaining items on the spreadsheet.
Now we can start deleting some code.
We should group some classes into dedicated packages by topic/function, for easier navigation and assessment.
