### ISSUE TITLE
Unicode Tools should not write literal control codes

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#2]
The Unicode Tools write some control codes that make a mess with various tools. For example, some files (e.g., IdnaTest.txt & CollationTest_NON_IGNORABLE.txt) have literal U+001A (^Z) which DOS/Windows tools recognize as an end-of-file marker, and some Linux tools say that such files are binary, not text, and so refuse to do text operations on them.

We should have a common piece of code that escapes such control codes, and use it from the tools.

**Comment by liancu-uni** [comment]
Similarly, sometimes a literal null (U+0000) is output, e.g., by the invariant tests.  The nulls cause truncation when trying to copy/paste (at least on Windows).

**Comment by macchiati** [comment]
Sound good.

There may be some circumstances where we want to test unusual characters,
but for those cases it sounds like we need to escape them.

**Comment by markusicu** [comment]
It might be that the newer files already have control codes escaped. I think I worked on that for the collation files...

**Comment by markusicu** [comment]
We can't find naked control codes in recent versions of generated files.
