### ISSUE TITLE
The root of https://util.unicode.org/ returns 404

### ISSUE THREAD

**Issue by mihnita** [unicode-org/unicodetools#20]
The 404 page contains a link (/UnicodeJsps) that takes me to a working page.

If moving the tools in the root is too hard then a simple index.html might be good enough.

Or maybe a redirect.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

----

The page looks something like this:

----------

## Error 404 - Not Found.
No context on this server matched or handled this request.

Contexts known to this server are:
| Context Path | Display Name | Status | LifeCycle |
| -- | -- | -- | -- |
| [/UnicodeJsps]() | UnicodeJsps | Available | STARTED |

**Comment by srl295** [comment]
== #19
