### ISSUE TITLE
make Unicode Tools work with CLDR 41

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#218]
The Unicode Tools do not work with the latest CLDR snapshot ([2022-apr-04](https://github.com/unicode-org/cldr/packages/521051)). I tried to pick it up like this:
```patch
diff --git a/pom.xml b/pom.xml
index d5dfbb3a..d60db5e8 100644
--- a/pom.xml
+++ b/pom.xml
@@ -31,7 +31,7 @@
                <!--
                         For CLDR versions, see https://github.com/orgs/unicode-org/packages?repo_name=cldr
                  -->
-               <cldr.version>0.0.0-SNAPSHOT-e995b07a7e</cldr.version>
+               <cldr.version>0.0.0-SNAPSHOT-1e28c0fbb4</cldr.version>
 
 
                <!-- these two set the JDK version for source and target -->
```

The Tools depend on the Xerces XML parser, which they used to get indirectly via CLDR. CLDR removed that dependency due to a Java 11 conflict: https://github.com/unicode-org/cldr/pull/1859

I tried copying the old Xerces Maven dependencies into the Unicode Tools pom.xml files (top + unicodetools) but then got the errors for the Java 11 conflict. I suspect that the Unicode Tools also need to switch to the built-in XML parser. Maybe we need to look at changes from more of the https://unicode-org.atlassian.net/browse/CLDR-14311 pull requests and make similar changes in the Tools?

This is blocking any kind of CLDR-vs-Unicode-Tools refactoring; in my case, I am attempting a refactoring of CLDR class UnicodeProperty and trying that out with Unicode Tools.

@srl295 could you please take a look?

**Comment by srl295** [comment]
Can you try removing xerces?

**Comment by markusicu** [comment]
> Can you try removing xerces?

I don't know what you mean? Remove it from where?

I have an otherwise unmodified Unicode Tools workspace where I tried to upgrade the CLDR dependency to the latest snapshot. That failed to build, complaining that it couldn't find any org.apache stuff including Xerces. Then I tried to add the Xerces dependency that CLDR used to have to Unicode Tools which used to just inherit it. Then I got the conflict errors.

That's what I did, that's all I know :-}

**Comment by markusicu** [comment]
It looks like this is blocking some work for @echeran now...

**Comment by srl295** [comment]
@markusicu  will take a look

**Comment by srl295** [comment]
> > Can you try removing xerces?
> 
> I don't know what you mean? Remove it from where?

For the record, to remove it from the `pom.xml` that mentions it.

**Comment by srl295** [comment]
@markusicu  going to call this done.  We're on early-CLDR-42-dev now.
