### ISSUE TITLE
Invalid connection between lb=SA and exclusion from GCB=SpacingMark

### ISSUE THREAD

**Issue by NorbertLindenberg** [unicode-org/unicodetools#222]
Lines 569-570 of unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt say “Ken: The postbase gc=Mc, InPC=Right characters (for these scripts with lb=SA) should be excluded from the set GCB=SpacingMark, and instead should fall through to GCB=XX.” Line 573 makes use of this connection by using lb=SA in the calculation of $PostBaseSpacingMarks_All.

I believe the connection between lb=SA and exclusion from GCB=SpacingMark made here is invalid. One is about a specific requirement for line breaking, the other about a desire to position cursors inside clusters (see [L2/11-114](https://www.unicode.org/cgi-bin/GetDocumentLink?L2/11-114), which apparently prompted the list of exclusions from SpacingMark). That both currently apply to subsets of the South East Asian scripts is irrelevant. That they are not the same is evidenced, for example, by Khmer characters being included in SpacingMark while having (and needing) lb=SA. I recommend removing that connection, and instead using an explicit list of scripts whose spacing marks should be excluded.

The comment in line 567 "Post-base spacing combining marks of most SE Asian scripts are explicitly excluded from GCB=SpacingMark" is also wrong. Most of the 26 south east Asian scripts in Unicode 15 are not affected by this.

The initially quoted comment has also been added to unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java, and should be corrected there at the same time.

**Comment by markusicu** [comment]
FYI

This is based on several email discussions, mostly between Norbert, KenW, Debbie, and myself, which started with an invariant-test failure involving some Kawi characters.

Ken wrote in 2021-dec:
> In this case I think the invariant test is correct. ...
> The *postbase* gc=Mc, InPC=Right characters (for these scripts with lb=SA) should be excluded from the set GCB=SpacingMark, and instead should fall through to GCB=XX. ...
> For Kawi, that should leave just 11F3E..11F3F as GCB=SpacingMark. Those are the *prebase* vowels. Cf. the treatment for U+11726 AHOM VOWEL SIGN E.

So I changed the data and the spec.
- https://github.com/unicode-org/unicodetools/pull/181
- https://github.com/unicode-org/unicode-reports/pull/30

Norbert took this back into the SAH which agreed with his analysis. Today in the UTC meeting we got action items to fix (undo) UAX 29 and the data file, for example:
> [171-A] Action Item for Markus Scherer, Properties & Algorithms Group: Exclude the following Kawi characters from having the Grapheme_Cluster_Break property value SpacingMark in GraphemeBreakProperty.txt (for Unicode version 15.0):
> U+11F03  KAWI SIGN VISARGA
> U+11F34  KAWI VOWEL SIGN AA
> U+11F35  KAWI VOWEL SIGN ALTERNATE AA
> U+11F41  KAWI SIGN KILLER

The UTC has also agreed with formalizing default line breaking for several scripts (including Kawi) along orthographic syllable boundaries.
