### ISSUE TITLE
Fix age of handshake emoji modifier sequences

### ISSUE THREAD

**Issue by nedley** [unicode-org/unicodetools#270]
emoji-test.txt lists these sequences as E3.0 after the handshake itself, but the sequences should be E14.0.

**Comment by markusicu** [comment]
@nedley @macchiati should this be fixed for Unicode 15?

**Comment by nedley** [comment]
I’d love to but only if I can find the time.

**Comment by markusicu** [comment]
> nedley linked a pull request 32 minutes ago that will close this issue

Curious: How did you link the PR and the issue without a visible line with some magic syntax?

**Comment by nedley** [comment]
I clicked the gear icon next to Development in the sidebar.
