### ISSUE TITLE
Jsps to Unicode 15 beta

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#271]
I suggest updating the Jsps to Unicode 15 beta, and advertising that on the unicode/unicore lists, to help with beta review.

@macchiati @srl295

**Comment by srl295** [comment]
followon to #140

**Comment by srl295** [comment]
- pull https://github.com/unicode-org/icu/releases/tag/cldr%2F2022-06-27
- pull similar CLDR version?

**Comment by macchiati** [comment]
Missed this earlier, yes, a good idea. I haven't looked at this in a while: The binary versions of the properties have to be updated in the jsp directories, and there is a switch that enables it. I think just the main version of CLDR would work.

**Comment by srl295** [comment]
@markusicu @macchiati  I see this:

> Z-Other … Emoji_Keycap_Sequence

**Comment by srl295** [comment]
OK. I'm able to build again. Now to make the build actually work..

**Comment by srl295** [comment]
Deployed to https://util.unicode.org/

**Comment by macchiati** [comment]
Added https://github.com/unicode-org/unicodetools/issues/336
