### ISSUE TITLE
CLDR website bug reporting link broken

### ISSUE THREAD

**Issue by villesinisalo** [unicode-org/unicodetools#285]
Hello!

First of all - I am very sorry for using this channel that is almost certainly incorrect for the purpose, but I do not know what else to do at this point.

I found a few issues with the [Unicode CLDR website](https://cldr.unicode.org/). There is a very prominent and (theoretically) helpful link on the very top of each page for reporting issues with the website. It redirects me to this URL (via google.com, which is actually the main issue I want to report ­­— all external links on the site are piped through google.com): https://sites.google.com/unicode.org/cldr/index/bug-reports

However, this website is not accessible to me (404), so I can not report my issues there. My theory is that the bug reporting site is only accessible with Google internal SSO.

So - I can not file a bug report on the CLDR website via the advertised "official" channel, and I am rising this ticket on your GitHub instead in hopes that I could find someone who can restore public access.

**Comment by srl295** [comment]
Hi. Thanks and understood about the channel. You can file CLDR  bugs at unicode-org.atlassian.net (make sure to set the project to CLDR. )

**Comment by srl295** [comment]
@villesinisalo the new home of that info is: https://github.com/unicode-org/cldr/blob/main/docs/requesting_changes.md
