### ISSUE TITLE
Consider test: InSc=Bindu --> Alphabetic with exceptions

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#289]
The [UTC 172 script ad hoc report](https://www.unicode.org/L2/L2022/22128-script-adhoc-rept.pdf) item VII 27 “Nonalphabetic bindus” points out that “Most characters with InSC=Bindu have Alphabetic=Yes.”

In discussion, attendees agreed, and wished for an invariant test, but there could be exceptions. Consider adding a test, with a comment that this is not a hard & fast rule, and to allow for exceptions.

**Comment by markusicu** [comment]
https://github.com/unicode-org/unicodetools/blob/main/docs/build.md#invariant-checking --> https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt

**Comment by markusicu** [comment]
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AInSc%3DBindu%3A%5D-%5B%3AAlphabetic%3A%5D&g=gc&i=

Currently 5 exceptions.
- is the rule roughly right?
- if so, are these intentional exceptions?
- otherwise, are these wrong? should these 5 be alphabetic?

**Comment by josh-hadley** [comment]
Once #318 is sorted, I will follow-up with SAH on the questions Markus mentions above.

**Comment by markusicu** [comment]
Thanks for the test!
Should we keep this issue open for the SAH review of the exceptions?
Or do you want to track that in some other way?

**Comment by josh-hadley** [comment]
I'd like to keep it open until we complete the review w/SAH (starting an email on that right now).

**Comment by josh-hadley** [comment]
@markusicu reviewing the discussion from UTC #172 on this, SAH determined that those 5 exceptions are in fact mistakes and should be changed to `Alphabetic=Yes` we have made that change in #296 (AI 172-A17). So probably that is why our original implementation of the rule failed -- the exceptions are already removed. The way the rule is written now passes even with the change in place, but I think it should actually be changed to `[\p{InSC=Bindu} - \p{Alphabetic}] = []`.

**Comment by macchiati** [comment]
Agreed.

**Comment by markusicu** [comment]
Thanks for following up, and sorry for the outdated info in this issue. I wrote this issue during the UTC meeting, apparently before the AI for the property change, or else not thinking of the connection.

@josh-hadley would you like to create another PR to empty out the exceptions and remove the TODO? I think we should leave the note that there *may* be exceptions.

**Comment by josh-hadley** [comment]
Yes, I will do that (already started a branch and confirmed that the invariant test passes with `[\p{InSC=Bindu} - \p{Alphabetic}] = []`), PR to follow soon.
