### ISSUE TITLE
Unable to run GenerateEmoji.java

### ISSUE THREAD

**Issue by nedley** [unicode-org/unicodetools#291]
```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage in both module java.base and module jrt.fs
```

I encountered this with Eclipse 2021.12 but upgrading to 2022.06 did not resolve it.

**Comment by nedley** [comment]
I am using the default Eclipse JDK, which is identified as “JRE [17.0.1]” at `/Users/ned/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.1.v20211116-1657/jre`.

**Comment by srl295** [comment]
> I am using the default Eclipse JDK, which is identified as “JRE [17.0.1]” at `/Users/ned/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.1.v20211116-1657/jre`.

I'll try it and look. May need to install a back level jre.

**Comment by srl295** [comment]
So far it's launched for me in the circled 3 environments.   Temurin 17.0.2, openjdk 11.0.14.1, and openjdk 18.0.2 

![image](https://user-images.githubusercontent.com/855219/181645719-2f5e2665-6722-4ec7-aaa0-19cc580e7e31.png)

**Comment by srl295** [comment]
didn't realize JustJ was a release… https://download.eclipse.org/justj/jres/17/updates/release/17.0.1/

**Comment by srl295** [comment]
@nedley  I installed the same exact JRE but could not reproduce it under eclipse 2022-03 (4.23.0)

**Comment by nedley** [comment]
OK, I will try another machine.

**Comment by nedley** [comment]
I reinstalled Eclipse and things are working again. Sorry for the hassle!

**Comment by srl295** [comment]
Glad it’s working, thanks for the report… It looked like there was a simple
bug somewhere
