### ISSUE TITLE
add Public/<version>/ReadMe.txt into the repo?

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#327]
For each data file folder that we track in the Unicode Tools repo, we include almost all of the files (with exceptions like a transmogrified form of the Unihan data) including ReadMe.txt files.

We are missing the UCD top-level readme: https://www.unicode.org/Public/15.0.0/ReadMe.txt

Consider adding it to the repo, so that we can track its contents and mostly publish the UCD from out of the repo.
Since the tools don't need access to multiple versions of this file at the same time, it could just go into unicodetools/data/ucd/ .

**Comment by markusicu** [comment]
We could give it a different name inside .../ucd/dev/

Easier to just put it into unicodetools/data/ucd/

**Comment by markusicu** [comment]
I am having second thoughts.
- This file is part of the set of UCD files for each version, so it does make sense to keep it in `dev` which would require a different filename.
- There is another ReadMe.txt file that is equally tied to the set of UCD files for each version, which means we need to get creative about filenames anyway: https://www.unicode.org/Public/zipped/15.0.0/ReadMe.txt

New proposal:
- Add https://www.unicode.org/Public/15.0.0/ReadMe.txt as .../data/ucd/dev/version-ReadMe.txt
- Add https://www.unicode.org/Public/zipped/15.0.0/ReadMe.txt as .../data/ucd/dev/zipped-ReadMe.txt

ok? @josh-hadley @echeran @macchiati @srl295

**Comment by echeran** [comment]
Makes sense, sounds ok to me

**Comment by josh-hadley** [comment]
no objections from me
