### ISSUE TITLE
u15: Z-Other: Emoji_Keycap_Sequence

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#335]
the properties demo shows Z-Other of `Emoji_Keycap_Sequence` per #271 - what is the action to take? #331 

Docs say 'go to XPropertiesFactory.java' but not much more - https://github.com/unicode-org/unicodetools/blob/92aa809458c9e5d1c2004883abefe90c48dd8622/docs/unicodejsps/index.md#addingupdating-new-properties

**Comment by srl295** [comment]
#331 is the ticket for docs updates

@markusicu @macchiati  it's not clear from XPropertyFactory what needs to be updated.

**Comment by macchiati** [comment]
I'll have to look at that. Usually that is a missing step from
https://github.com/unicode-org/unicodetools/blob/main/docs/newunicodeproperties.md
.

added to https://github.com/unicode-org/unicodetools/issues/336

**Comment by markusicu** [comment]
closed as superseded by 336
