### ISSUE TITLE
The Character Properties utility should support U+ notation

### ISSUE THREAD

**Issue by eggrobin** [unicode-org/unicodetools#350]
From @PeterConstable on properties@unicode.org, 2022-08-17:
> Why doesn’t the [Character Properties utility](https://util.unicode.org/UnicodeJsps/character.jsp?a=5&B1=Show) allow you to type code points in “U+” notation, which is the conventional citation form for code points?

> After trying that and getting properties for “U”, it’s not at all obvious that the non-conventional form without “U+” would work, though I suppose one might argue that the report shows the other form.

I replied:
> I have been bitten by that and shown the properties of LATIN CAPITAL LETTER U many times, so I very much agree that this should support U+ notation.

> This should be easy enough to add, the parsing code appears to be [here](https://github.com/unicode-org/unicodetools/blob/70dce2c89f185c65b436c28404ae5b7bdb32c2d1/UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeJsp.java#L211) (called from [here](https://github.com/unicode-org/unicodetools/blob/fc25a0e1d7b1123bc8da239cd7a9c7f98f6e8a90/UnicodeJsps/src/main/webapp/character.jsp#L27)), but I have yet to do the [setup](https://github.com/unicode-org/unicodetools/blob/main/docs/unicodejsps/index.md) to build this stuff.

KenW replied:

> For what it is worth, the Code2Chart code chart lookup CGI utility used on the code charts index page:

> https://www.unicode.org/charts/

> has long supported entry as U+212A, as well as \u212A, \U212A, and for that matter 0x212A, as well as bare hex entry 212A, and lowercase hex digits, too, too: 212a, face, etc.

**Comment by markusicu** [comment]
It would also be nice to have a little help text near the input field that says that you can enter a character or its hex code point.

And, maybe show an error if it doesn't fit one of the hex patterns but is more than one character.

**Comment by eggrobin** [comment]
> And, maybe show an error if it doesn't fit one of the hex patterns but is more than one character.

Maybe even show links to the pages for each character in that case. I often want to look at a combining mark from some grapheme cluster, for instance.

**Comment by eggrobin** [comment]
Amusing find while playing with that: the tool does not support HTML escapes, but it outputs them unescaped, showing the properties of & while displaying the unescaped character: https://util.unicode.org/UnicodeJsps/character.jsp?a=%26%23x2615%3B&B1=Show
