### ISSUE TITLE
delete all but one *Invariant*.txt

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#380]
[In the repo, use "Go to file"](https://github.com/unicode-org/unicodetools/find/main) and look for files named like "invariant.txt". There is a confusing set of similarly-named files. Some of them are old according to their names or in-file comments.

The "real" invariants test file is https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt

Can we delete each of the others? Or is any one of them still used by some code?
- (?) https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/InvariantTest.txt
- (says "OLD") https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariants.txt
- (named "attic...") https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/atticUnicodeInvariants.txt
- (empty, named "scratch...") https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/ScratchInvariantTest.txt
- (named "reallyold") https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariants-reallyold.txt

**Comment by macchiati** [comment]
You can remove all but the "real" one:
