### ISSUE TITLE
CI workflow to keep Maven artifact cache fresh

### ISSUE THREAD

**Issue by echeran** [unicode-org/unicodetools#421]
In #418, Unicode Tools' CI on Github Actions is experiencing the same problem as the CI for ICU's Maven build, which is that we have ephemeral download errors from Maven Central (for some reason on the same artifact), and the cache TTL for Github Actions is only 7 days.

We can copy [my workaround in ICU](https://github.com/unicode-org/icu/pull/2281), which is just to make use of the cache regularly with period < TTL.

**Comment by srl295** [comment]
Sgtm as a workaround. Other options 

- more aggressive retry ?
- use alternate maven mirrors ?
