### ISSUE TITLE
https://util.unicode.org/ 403 Forbidden?

### ISSUE THREAD

**Issue by x11x** [unicode-org/unicodetools#523]
I am a bit confused whether the unicodetools JSPs hosted at https://util.unicode.org/ are supposed to be publicly available (I believe they used to be). I get 403 Forbidden for everything on https://util.unicode.org/

Example link:
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AXID_Start%3A%5D&abb=on&g=&i=

I am reporting this based on the CLDR links migrating banner on https://cldr.unicode.org/unicode-utilities - it does say they "will be removed...", but I wasn't clear if that meant they will no longer be publicly available anywhere, or if that meant they would just be removed from cldr.unicode.org

Apologies if I've missed an issue or announcement

**Comment by macchiati** [comment]
That's a misleading message. There is a problem with the server that might
take some time to fix but we plan to have them back up.

**Comment by srl295** [comment]
working on it

**Comment by srl295** [comment]
@x11x meanwhile, if you have Docker you can run:

`docker run --rm -p 8080:8080 unicode/unicode-jsp`

**Comment by srl295** [comment]
fixed
