### ISSUE TITLE
UnicodeSet util: Extended_Pictographic missing unassigned code points

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#53]
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AExtPict%3A%5D%26%5B%3ACn%3A%5D&g=&i= comes up empty but should show more than 1000 unassigned code points such as the following.

https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt
```
1F0D0..1F0FF  ; Extended_Pictographic# E0.0  [48] (🃐..🃿)    <reserved-1F0D0>..<reserved-1F0FF>
...
1F8AE..1F8FF  ; Extended_Pictographic# E0.0  [82] (🢮..🣿)    <reserved-1F8AE>..<reserved-1F8FF>
...
1FC00..1FFFD  ; Extended_Pictographic# E0.0[1022] (🰀..🿽)    <reserved-1FC00>..<reserved-1FFFD>
```
@macchiati FYI

**Comment by macchiati** [comment]
Thanks. I need to fix the underlying code. There is a property flag that says "I have all the same values for unassigned code points", in place for performance. That flag is manually set, but should be computed at build time instead.

**Comment by markusicu** [comment]
Mark said in https://github.com/unicode-org/unicodetools/issues/97#issuecomment-883030395 that this issue here is a duplicate of the newer one, and the newer one has more information.
