### ISSUE TITLE
allkeys_CLDR.txt contains variable collation elements with an ignorable primary weight

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#572]
From CLDR-17161 reported by Henry Stratmann

The version of allkeys.txt that is generated by the Unicode Tools Java code (rather than the C sifter code) generates some secondary CEs that are marked with a star for being “variable”. This is visible in [CLDR 44 allkeys_CLDR.txt](https://github.com/unicode-org/cldr/blob/maint/maint-44/common/uca/allkeys_CLDR.txt) for the non-ASCII apostrophe and quotation mark characters which now have merely secondary distinctions from the ASCII ones. Look for `[*0000.`:
```
0027  ; [*022E.0020.0002] # APOSTROPHE
FF07  ; [*022E.0020.0003] # FULLWIDTH APOSTROPHE
2018  ; [*022E.0020.0004][*0000.011C.0004] # LEFT SINGLE QUOTATION MARK
2019  ; [*022E.0020.0004][*0000.011D.0004] # RIGHT SINGLE QUOTATION MARK
201A  ; [*022E.0020.0004][*0000.011E.0004] # SINGLE LOW-9 QUOTATION MARK
201B  ; [*022E.0020.0004][*0000.011F.0004] # SINGLE HIGH-REVERSED-9 QUOTATION MARK
05F3  ; [*022E.0020.0004][*0000.0124.0004] # HEBREW PUNCTUATION GERESH
2039  ; [*022F.0020.0002] # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
```
(same for the double quote variants)

Variable primaries (with a star) should not be zero: https://www.unicode.org/reports/tr10/#File_Format

**Comment by markusicu** [comment]
It looks like the code that prints the CEs is in https://github.com/unicode-org/unicodetools/blob/main/unicodetools/src/main/java/org/unicode/text/UCA/UCA.java functions toStringUCA() and isVariablePrimary().

The latter has
```
        return primary == 0 ? lastWasVariable : primary <= variableTop && variableBottom <= primary;
```
which means that if an ignorable CE follows a variable one, then the ignorable one "inherits" the variable-ness.

I don't know why it does that. As CLDR-17161 quotes the spec, this is wrong. And these non-initial, ignorable CEs are not marked as variable in the DUCET allkeys.txt:
```
2018  ; [*0337.0020.0004][.0000.011E.0004] # LEFT SINGLE QUOTATION MARK
201C  ; [*033A.0020.0004][.0000.011E.0004] # LEFT DOUBLE QUOTATION MARK
2019  ; [*0337.0020.0004][.0000.011F.0004] # RIGHT SINGLE QUOTATION MARK
```

Also, I don't understand the condition `variableBottom <= primary`. Any primary between 0 and variableTop is variable, right? Why is there even a variableBottom variable here?

@macchiati (a) Why does the Java code write allkeys_CLDR.txt and allkeys_DUCET.txt with variable ignorables? and (b) why do we have and look at `variableBottom`?

**Comment by markusicu** [comment]
I found an answer for why we have variableBottom, and added a comment about it into the code.

**Comment by macchiati** [comment]
I think I remember a reason for special behavior, perhaps misapplied. If
you have a variable base character (eg space or @) that is followed by a
non-spacing mark, then you want the non-spacing mark to *also* become
variable.

**Comment by markusicu** [comment]
> I think I remember a reason for special behavior, perhaps misapplied. If you have a variable base character (eg space or @) that is followed by a non-spacing mark, then you want the non-spacing mark to *also* become variable.

Not exactly. When alternate=shifted, then any ignorable CE that follows a variable one is completely ignored. But that happens _in processing_, not in the data file. In particular, when you have text with two characters where the first maps to a variable CE and the second to an ignorable CE, you still need to drop the second one for shifted, but since they are separate mappings, there is nothing you can do in the data file to indicate that. The CE for the same second character is kept as is if it follows a regular letter.

Looking at the file format definition, as the bug reporter said, marking ignorable CEs as variable in the allkeys.txt file is just wrong.
