### ISSUE TITLE
online demos: update the bidi reference c code for Unicode 15.1

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#573]
@Ken-Whistler has the bidiref1.exe updated for Unicode 15.1, ready to go, and asking where to put or send it.
What's next?
@srl295 @josh-hadley @eggrobin @macchiati

**Comment by srl295** [comment]
the source (not the exe) needs to go into https://www.unicode.org/Public/PROGRAMS/BidiReferenceC/ - looks like https://www.unicode.org/Public/PROGRAMS/BidiReferenceC/15.1.0/ is correct?

**Comment by srl295** [comment]
… then it's a matter of updating https://github.com/unicode-org/unicodetools/blob/main/UnicodeJsps/Dockerfile#L6

**Comment by Ken-Whistler** [comment]
O.k., yes, I already posted the updated bidiref1.c to PROGRAMS/BidiReferenceC/:
https://www.unicode.org/Public/PROGRAMS/BidiReferenceC/15.1.0/source/bidiref1.c
So my part should be done.
