### ISSUE TITLE
UTS #18 — 3 CJK Properties

### ISSUE THREAD

**Issue by macchiati** [unicode-org/unicodetools#625]
Consider proposing adding some Unihan properties to Full Properties in UTS18, from https://www.unicode.org/reports/tr38/#AlphabeticalListing

We can exclude a few:
- Status=Provisional — those are unsuited for regex
- Category=IRG Sources — specialized character code mappings*
- Dictionary-like Data, Readings — too specialized for general regex

That leaves the following:

kAccountingNumeric | Informative | Numeric Values
-- | -- | --
kOtherNumeric | Informative | Numeric Values
kPrimaryNumeric | Informative | Numeric Values

Notes:
- kTotalStrokes, kRSUnicode, and kMandarin are Normative for CLDR, even though marked as Informative in UAX38
- The Catagory for kTotalStrokes, kRSUnicode seems odd; the rest are specialized character code mappings

**Comment by markusicu** [comment]
Why would we recommend the kXyzNumeric properties?

(a) I don't think the numeric values are all that useful, except of course for values of decimal digits.

(b) If one of these is set, then it already shows up in the UCD Numeric_Value.

**Comment by macchiati** [comment]
Good point. Closing this.
