### ISSUE TITLE
Update pom.xml to use CLDR 44.1

### ISSUE THREAD

**Issue by nedley** [unicode-org/unicodetools#641]
I need the fix for CLDR-17230 but apparently unicodetools is not yet configured for CLDR 44.1 nor ICU 74.2.

**Comment by srl295** [comment]
CLDR version for 44.1 is:  `<version>0.0.0-SNAPSHOT-880c12f291</version>`
looks like for icu4j you be able to use `<version>74.2-SNAPSHOT</version>` - my consternation may have been unfounded

**Comment by srl295** [comment]
@nedley may just need numbers above ^

**Comment by srl295** [comment]
Ok good

--
Steven R. Loomis
Code Hive Tx, LLC
https://codehivetx.us

**Comment by nedley** [comment]
Overlapping comments, ahh! Thanks for the quick resolution, I will contact Mark about the results.

**Comment by nedley** [comment]
As for ICU, I tried https://github.com/unicode-org/icu/packages/411079 but Eclipse says there are errors.
