### ISSUE TITLE
Fix PropertyValueAliases for Teh_Marbuta_Goal ; Hamza_On_Heh_Goal

### ISSUE THREAD

**Issue by macchiati** [unicode-org/unicodetools#642]
REPLACED BY https://github.com/unicode-org/properties/issues/231

**Comment by markusicu** [comment]
I added this to both the PAG and Unicode Tools dashboards.

Formally speaking, there is no defect here. There are two aliases, they differ, they just happen to be more different than "short vs. long".

I agree that the UTC should have a consensus + AI to change this.

**Comment by markusicu** [comment]
@eggrobin @josh-hadley FYI

**Comment by markusicu** [comment]
And, as Robin pointed out: the decision to add the name Teh_Marbuta_Goal was https://www.unicode.org/L2/L2010/10015.htm#122-C4.

**Comment by macchiati** [comment]
REPLACED BY https://github.com/unicode-org/properties/issues/231
