### ISSUE TITLE
Missing @missing for ArabicShaping.txt

### ISSUE THREAD

**Issue by macchiati** [unicode-org/unicodetools#644]
REPLACED BY https://github.com/unicode-org/properties/issues/230

**Comment by roozbehp** [comment]
> 3. **Radical change.** Deprecate ArabicShaping.txt and make the DerivedJoiningGroup and DerivedJoiningType be the source of truth. That would be the cleanest approach, but is probably a bridge too far, even for me.

Yeah, too far. Note that the file also includes schematic names which is useful for both font designers and character encoders (I rely on it to make sure we have not already encoded a proposed Arabic character, since there's so many of them and they are not really organized by any rules).

**Comment by markusicu** [comment]
Why is this a unicodetools issue and not a PAG issue? I just added it to both dashboards.

If we decide that this file needs to be parseable in the usual UCD way, then I think we should do option 1 -- explicitly list the T data lines, and set the `@missing` value to U.

Needs UTC consensus+AI.

**Comment by macchiati** [comment]
REPLACED BY https://github.com/unicode-org/properties/issues/230
