### ISSUE TITLE
Add variation selectors to the "alt=''" tags in the "Emoji Presentation Sequences" page (emoji-variants.html)

### ISSUE THREAD

**Issue by kenlunde** [unicode-org/unicodetools#700]
If someone attempts to copy from the "Sample Text" or "Sample Emoji" columns of the [Emoji Presentation Sequences](unicode.org/emoji/charts-15.1/emoji-variants.html) page, what they copy does not include the variation selector. The relevant HTML excerpts are below:

```
Sample Text: alt='♟'
Sample Emoji: alt='♟'
```

When one copies either image, what they get is `U+265F ♟ BLACK CHESS PAWN` as an atomic character with no variation selector.

What I suggest is that the tools be adjusted so that they emit the variation sequences in these HTML `alt=''` blobs, and in a form that is human-readable using Numeric Character References:

```
Sample Text: alt='&#x265F;&#xFE0E;'
Sample Emoji: alt='&#x265F;&#xFE0F;'
```

I confirmed that copying the image results in copying the variation sequence.

**Comment by nedley** [comment]
The 16.0 final charts contain non-escaped `alt` tags for the moment, I will work out the escaping before merging the code.

**Comment by nedley** [comment]
OK, `alt` attributes are escaped in the charts. The code, on the other hand, requires a small amount of untangling before it is ready.
