### ISSUE TITLE
jsp: E000 in characters.jsp shows as FFFD

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#725]
https://util.unicode.org/UnicodeJsps/character.jsp?a=E000
PUA, but the glyph shown and copied is FFFD

**Comment by macchiati** [comment]
The character used to show that glyph is fine. Using the actual character
did not work well (invisible, box, other random stuff).

One could use a colored version to signal more info, maybe a graphic
instead (so copying would not get FFFD), but I think this is low priority.
Maybe do if that page is being touched anyway.

**Comment by srl295** [comment]
> The character used to show that glyph is fine.

E000 isn't FFFD though, so why should it show up as missing?

> Using the actual character did not work well (invisible, box, other random stuff).

could be a good job for [notdef](https://github.com/adobe-fonts/adobe-notdef) or [last-resort-font](https://github.com/unicode-org/last-resort-font) right? 

> One could use a colored version to signal more info, maybe a graphic instead (so copying would not get FFFD), but I think this is low priority. Maybe do if that page is being touched anyway.

**Comment by kenlunde** [comment]
The problem is that _any_ unassigned code point, PUA or otherwise, becomes U+FFFD. For example, if one selects the glyph that appears, its code point is U+FFFD, not the code point that was entered. This feels misleading.

About how an unassigned code should appear, _Last Resort_ will provide the most meaningful glyph.

**Comment by macchiati** [comment]
E000 has no specific display at all, that's the problem. But showing blank
is also wrong, since that implies that it is either a space or an invisible
glyph.

https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5CuE000&g=gc&i=

**Comment by macchiati** [comment]
That's a good suggest, Ken. We could implement this with a Web Font version of the LRF.

> The problem is that _any_ unassigned code point, PUA or otherwise, becomes [U+FFFD](https://util.unicode.org/UnicodeJsps/character.jsp?a=FFFD). For example, if one selects the glyph that appears, its code point is [U+FFFD](https://util.unicode.org/UnicodeJsps/character.jsp?a=FFFD), not the code point that was entered. This feels misleading.
> 
> About how an unassigned code should appear, _Last Resort_ will provide the most meaningful glyph.

**Comment by eggrobin** [comment]
I tried to do that; see it in staging at https://unicode-jsps-staging-o2ookmn2oq-uc.a.run.app/UnicodeJsps/character.jsp?a=100000&B1=Show&history=full&showDevProperties=1.

**Comment by srl295** [comment]
Nice!!

**Comment by eggrobin** [comment]
Now live at https://util.unicode.org/UnicodeJsps/character.jsp?a=100000&history=full&showDevProperties=1.
