### ISSUE TITLE
The JSPs are flaky

### ISSUE THREAD

**Issue by eggrobin** [unicode-org/unicodetools#728]
Since I pushed the new JSPs incorporating #432 and #502, they have tended to 500 on list-unicodeset.

(Originally filed as https://github.com/unicode-org/properties/issues/258.)

**Comment by eggrobin** [comment]
Observations before I forget them:
- they seem a great deal less flaky this morning (my time).
- last night I saw a lot of logs calling out that we were constructing the full UnicodeMap (which we generally don’t want to do), probably to list the values, in turn perhaps to count them. As I had noted before, this is daft and optimizable if done directly in (Index)UnicodeProperty.

**Comment by eggrobin** [comment]
I think I see what is going on. I screwed up the startup sequence, so we start serving after we have 15.1 loaded, but before 16.0α. The initialization of some classes relies on having 16.0α, so if someone looks at the JSPs in the few seconds before 16.0α is loaded, we get an exception in the initializer, and then the server is dead in the water.

**Comment by macchiati** [comment]
Makes sense.
