### ISSUE TITLE
IdnaTestV2.txt should test for valid input with upper case in the ASCII part of Punycode

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/unicodetools#747]
IdnaTestV2.txt missed a bug in the UTS 46 implementation that I'm writing due to not testing an upper-case letter in the ASCII part of Punycode when there are no errors.

I suggest adding this test case:

Input: `xn--A-1ga`
Expected ToASCII: `xn--a-1ga`
Expected ToUnicode: `aö`

**Comment by markusicu** [comment]
@macchiati FYI

**Comment by macchiati** [comment]
I agree; good idea. I recall that it is pretty easy to add special cases to
the test data. Markus, I can take this one if you like.

**Comment by markusicu** [comment]
Feel free to take this -- and remember your action item to review other bugs in the test data :-) --> https://github.com/unicode-org/properties/issues/162
