### ISSUE TITLE
Should `EA=N|Na` excluded from the `W` set?

### ISSUE THREAD

**Issue by kojiishi** [unicode-org/unicodetools#768]
This issue is a continuation of https://github.com/kojiishi/unicode-auto-spacing/issues/21.
@asmusf @xfq @kenlunde

**Comment by kojiishi** [comment]
Forked from the [diff review comments](https://github.com/kojiishi/unicode-auto-spacing/pull/20).

# A700-A707
@xfq:
> A700..A707 can be used in IPA, so adding extra spacing would be a bit weird.

@asmusf:
> My reaction would be: if something "can" be used with proportional spaced text it should have the equivalent of EAW=A.
> Because if it is not used for IPA, spacing may well be appropriate.

* [UnicodeSet](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5CuA700-%5CuA707%5D&g=&i=gc%2Csc%2Cscx%2Cea)
* [Code charts](https://www.unicode.org/charts/PDF/UA700.pdf)

So the question is whether these code points are used in non-Chinese context or not. The names contain "CHINESE TONE", but the script extension is `Hani|Latn`.

Does anyone know why these code points 1) have `Latin` in the script extensions, and 2) has EAW=`N`?

# 02EA..02EB
@xfq:
> 02EA..02EB are used together with Bopomofo, so I tend to think extra spacing should be added.

@asmusf:
> My thinking is that we should not attempt to be entirely context free, but to build in one switch (like the EAW=A property) that allows the default to work in the two common use cases (characters are used in EA context and are not used in EA context).

* [UnicodeSet](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5Cu02EA-%5Cu02EB%5D&g=&i=gc%2Csc%2Cscx%2Cea)
* [Code charts](https://www.unicode.org/charts/PDF/U02B0.pdf)

Their script is just `Bopo`, so auto-spacing `W` looks reasonable to me. @asmusf Do you know why they have EAW=`N`?

**Comment by xfq** [comment]
> @xfq, when you said "can be used in IPA", do you know other usages? Are there any cases where they present ideographic characters?

They are also used together with Chinese characters, but they do not belong to ideographic characters per se. See https://en.wikipedia.org/wiki/Four_tones_(Middle_Chinese)#Distribution_in_modern_Chinese_and_Sino-Vietnamese (search "꜀" in the page) for an example.

See also https://ja.wiktionary.org/wiki/%EA%9C%80 .

**Comment by kojiishi** [comment]
Thanks. So IIUC @xfq's recommendation is:
* Keep 02EA..02EB as W.
* Change A700-A707 to O.

Because both ranges are EA=N, we need to do something special for this case. Let me try.

**Comment by kojiishi** [comment]
For `ea=N|Na`, the following rules seem to work.
* If the script property is one of CJK, include `ea=N|Na`.
* Otherwise, if the script extension proeprty is one of CJK, exclude `ea=N|Na`.

The [diff here](https://github.com/kojiishi/unicode-auto-spacing/pull/20/files).

**Comment by kojiishi** [comment]
Fixed by https://github.com/kojiishi/unicode-auto-spacing/pull/20
