### ISSUE TITLE
Are part of CJK Unified Ideographs O?

### ISSUE THREAD

**Issue by kojiishi** [unicode-org/unicodetools#770]
This issue is a continuation of https://github.com/kojiishi/unicode-auto-spacing/issues/23, originally reported by @747

**Comment by kojiishi** [comment]
Originally reported by @747

**Comment by kojiishi** [comment]
Thank you for spotting this issue. Yes, this is because the PyICU library has old data. I'm thinking to switch to other libraries but it hasn't happened yet.

**Comment by kenlunde** [comment]
In addition to the issues that @747 pointed out, the following CJK Unified Ideographs that were added in Unicode Versions 15.0 or 15.1, which should have `W` as their property value, are missing altogether:

Version 15.0:
```
2B739
31350..323AF
```

Version 15.1:
```
2EBF0..2EE5D
```
Based on this, the data that was used to derive the property values was aligned with Unicode Version 13.0.

**Comment by markusicu** [comment]
> Thank you for spotting this issue. Yes, this is because the PyICU library has old data.

The PyICU maintainer is always quick to support many versions of ICU including the latest one. In fact, he is now looking into support for ICU 75 which is still in release candidate.

So if PyICU gives you old Unicode data, then that's because you are using it with an old version of ICU.

**Comment by kojiishi** [comment]
Thank you @kenlunde, this is very helpful to check the fix!

@markusicu I see, thank you. I'll switch to a library that reads the UNIDATA directly to avoid it.

**Comment by kojiishi** [comment]
Fixed by https://github.com/kojiishi/unicode-auto-spacing/pull/25.
