### ISSUE TITLE
The Auto Spacing model should not call for adding U+0020 SPACE by default to indicate an EA Spacing opportunity

### ISSUE THREAD

**Issue by kojiishi** [unicode-org/unicodetools#772]
@macnmm @asmusf Is this a good summary of the emial discussion? Please add if any.

This looks like related with #771 @PeterConstable.

**Comment by macnmm** [comment]
I agree with not adding space characters for this, yes.

**Comment by kojiishi** [comment]
Done by the PR https://github.com/kojiishi/unicode-auto-spacing/pull/31. Please let me know if any.
