### ISSUE TITLE
Add Mandombe to the Provisionally Assigned

### ISSUE THREAD

**Issue by Ashtontameirao** [unicode-org/unicodetools#872]
Mandombe is a popular script in Africa and should be added to the Provisionally Assigned for a Future Update.

**Comment by markusicu** [comment]
Mandombe is listed on the roadmap for plane 1, with a link to a 2016 proposal: https://www.unicode.org/roadmaps/smp/

If you have questions about the status of the proposal, please contact the Script Encoding Working Group of the UTC: https://www.unicode.org/consortium/scriptadhoc.html

If in doubt, use the Unicode contact form: https://www.unicode.org/reporting.html

This repo here is not appropriate for script encoding proposal requests or discussion.
