### ISSUE TITLE
New Block: Whitehall Eagles (U+C0000-U+C00FF) New Plane: Legacy Symbol Plane, Plane 12 (LSP)

### ISSUE THREAD

**Issue by Ashtontameirao** [unicode-org/unicodetools#873]
There are these eagles over the houses and should get added to the Provisionally Assigned and will add only 4 characters.
![Screenshot (1)](https://github.com/unicode-org/unicodetools/assets/173515737/c1986ae4-4f35-4ce8-b33f-00542c9bb729)
U+C0000 - 󀀀
![Screenshot (4)](https://github.com/unicode-org/unicodetools/assets/173515737/f73f5c15-1fa2-4e53-9945-8bc4265fcaef)
U+C0001 - 󀀁
![Screenshot (5)](https://github.com/unicode-org/unicodetools/assets/173515737/12e2c9b7-3b34-4c48-ba2b-a9427d5e9996)
U+C0002 - 󀀂
![Screenshot (6)](https://github.com/unicode-org/unicodetools/assets/173515737/02b2015f-36d0-44d7-b3b8-b11ee50cb604)
U+C0003 - 󀀃

**Comment by markusicu** [comment]
These are not characters.
Please do not abuse this issue tracker.

**Comment by Ashtontameirao** [comment]
I will need you to put this new block in plane 1, I have a suggestion made and should be added to the roadmap.
