### ISSUE TITLE
Argpal and Bete Syllabary Should be listed in the SMP Roadmap. (Plane 1)

### ISSUE THREAD

**Issue by Ashtontameirao** [unicode-org/unicodetools#875]
![udhr_argpal](https://github.com/unicode-org/unicodetools/assets/173515737/2d6088bd-bcb4-4e50-9f30-876a9995959f)
Argpal (U+1E090 - U+1E0FF)

![download](https://github.com/unicode-org/unicodetools/assets/173515737/abb5bd40-27ef-45c5-87cc-a1f4fa6e1446)
Bete Syllabary (U+15200 - U+154FF)

There are 2 scripts that needed to go to the roadmap, Argpal is a script created by JP Mallaroni and Bete Syllabary is an African script with a ton of syllables.

That's all I have to say but I have suggested 2 new scripts for this so bye!

**Comment by markusicu** [comment]
Once more, this issue tracker is not appropriate for general feedback or script proposals, and these are not actionable proposals. Please use the usual channels.
- https://www.unicode.org/reporting.html
- https://www.unicode.org/pending/docsubmit.html
