### ISSUE TITLE
emoji data is under 14.0 instead of 14.0.0

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#90]
can the emoji data use the same numbering?

**Comment by macchiati** [comment]
The question needs more context.

Mark

**Comment by srl295** [comment]
> The question needs more context.

Other subdirectories of `unicodetools/unicodetools/data/` use three-part version numbers, some with `-Update`:

```
unicodetools/data/security:
10.0.0			12.1.0			7.0.0			confusables-old.txt	revision-04
…

unicodetools/data/uca:
10.0.0	12.0.0	13.0.0	3.0.1	4.0.0	5.0.0	5.2.0	6.1.0	6.3.0	8.0.0
…

unicodetools/data/ucdxml:
10.0.0	11.0.0	12.0.0	12.1.0	13.0.0	6.3.0	7.0.0	8.0.0	9.0.0
…

unicodetools/data/ucd:
1.1.0-Update	12.1.0-Update	2.1.5-Update	3.0.1-Update	4.0.0-Update	5.1.0-Update	6.2.0-Update	9.0.0-Update
…
unicodetools/data/idna:
10.0.0	11.0.0	12.0.0	12.1.0	13.0.0	5.2.0	6.0.0	6.1.0	6.2.0	6.3.0	7.0.0	8.0.0	9.0.0
```

However, emoji uses a two-part version number:

```
unicodetools/data/emoji:
1.0	11.0	12.0	12.1	13.0	13.1	2.0	3.0	4.0	5.0	6.0
```


Is this just an inconsistency, or is it really a different version number?  UnicodeVersion=14.0.0, EmojiVersion=13.1 ?

**Comment by macchiati** [comment]
No particularly good reason.

Unicode allows for and uses 3 fields sometimes. We didn't sync the emoji
version with the Unicode version until recently, and hadn't needed 3 fields
for emoji. It's baked into https://unicode.org/Public/emoji/, so we
shouldn't change that without go-ahead from the UTC. The internal
directories in unicodetools could be different if necessary, of course.

Mark

**Comment by markusicu** [comment]
Closing this issue:
- The folders with version number names should match those in /Public/.
- I suspect that the Public folders will retain their naming scheme until we really need an emoji release like 15.0.1 or 15.1.1.
