### ISSUE TITLE
Please Encode for a future update of the Aymara and Paucartambo Script

### ISSUE THREAD

**Issue by MatthewtheUnicoder** [unicode-org/unicodetools#934]
Dear Unicode

So, I have two writing systems I can't find on Google search, Unicode must have found these two writing systems for a future encoding
 Right now they're not on the roadmap page. I have two writing systems that have images.

Aymara Ideographs
![Screenshot (13)](https://github.com/user-attachments/assets/cbd79c36-6317-4231-9804-f7a9be01a8a9)

Paucartambo
![Screenshot (12)](https://github.com/user-attachments/assets/d0e2eb5a-3c2e-4d65-b5f3-38fbf401c357)

So I want you to add these two writing systems to be known and make a PDF to see all the Characters from the Aymara and Paucartambo script too add to the roadmap and Future Encode these two writing systems.

I hope you reply something nice and to encode these writing systems!

Love, Matthew

**Comment by roozbehp** [comment]
You need to write a proposal and submit it. Here are the instructions: https://www.unicode.org/pending/proposals.html

**Comment by MatthewtheUnicoder** [comment]
How to I email the proposals to Unicode on Gmail?

**Comment by roozbehp** [comment]
> How do I email the proposals to Unicode on Gmail?

Here are the instructions: https://www.unicode.org/pending/docsubmit.html

**Comment by markusicu** [comment]
These two are on https://www.unicode.org/roadmaps/not-the-roadmap/
-->
Things rumored to be scripts, but not clearly enough attested for us to even determine whether they are "known scripts".
- Aymara
- Paucartambo
- ...
